name: virtkick
image: centos-7-0-x64
min_size: 2gb
config:
  #cloud-config
  runcmd:
    - yum install https://github.com/virtkick/virtkick-package/releases/download/0.4.alpha/virtkick-0.4.alpha-1_x86_64.rpm
